# Generated by Django 4.1.7 on 2023-03-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_artiles_options_alter_artiles_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='primary_key',
            field=models.CharField(max_length=10, verbose_name='Ключ'),
        ),
    ]
